import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import { validateCatalog } from '../src/lib/catalog.ts';

const repo = path.resolve('.'); const cli = path.join(repo, 'node_modules/.bin/tsx'); const pdf = Buffer.from('%PDF-1.4\n%%EOF\n'); const alternate = Buffer.from('%PDF-1.4\nreplacement\n%%EOF\n');
function setup() { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'freeedu-ingest-')); fs.mkdirSync(path.join(root, 'content')); fs.mkdirSync(path.join(root, '.storage/r2/files'), { recursive: true }); fs.writeFileSync(path.join(root, 'content/subjects.json'), JSON.stringify([{ id: 'subject-math', slug: 'mathematics', name: 'Mathematics', description: 'Study mathematics.' }])); fs.writeFileSync(path.join(root, 'content/topics.jsonl'), '{"id":"topic-algebra","slug":"algebra","subjectId":"subject-math","title":"Algebra","description":"Study algebra."}\n'); fs.writeFileSync(path.join(root, 'content/assets.jsonl'), ''); fs.writeFileSync(path.join(root, 'content/materials.jsonl'), ''); fs.writeFileSync(path.join(root, 'content/redirects.jsonl'), ''); const input = path.join(root, 'first.pdf'); const second = path.join(root, 'renamed.pdf'); const replacement = path.join(root, 'replacement.pdf'); fs.writeFileSync(input, pdf); fs.writeFileSync(second, pdf); fs.writeFileSync(replacement, alternate); return { root, input, second, replacement }; }
function run(root: string, args: string[]) { const result = spawnSync(cli, [path.join(repo, 'scripts/ingest.ts'), ...args], { cwd: root, encoding: 'utf8' }); assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`); }
test('actual CLI deduplicates identical filenames/content and preserves replaced assets before verified GC', () => { const f = setup(); const base = ['add', '--id', 'material-one', '--slug', 'one', '--title', 'One', '--description', 'One.', '--subject', 'subject-math', '--topics', 'topic-algebra']; run(f.root, [...base, '--file', f.input]); run(f.root, ['add', '--id', 'material-two', '--slug', 'two', '--title', 'Two', '--description', 'Two.', '--subject', 'subject-math', '--topics', 'topic-algebra', '--file', f.second]); let catalog = validateCatalog(f.root); assert.equal(catalog.assets.length, 1); const old = catalog.assets[0].id; run(f.root, ['replace', 'material-one', f.replacement]); catalog = validateCatalog(f.root); assert.equal(catalog.assets.length, 2); assert.ok(fs.existsSync(path.join(f.root, '.storage/r2/files', `${old}.pdf`))); });
test('GC refuses before verified deployment and protects manifest references', () => { const f = setup(); run(f.root, ['add', '--id', 'material-one', '--slug', 'one', '--title', 'One', '--description', 'One.', '--subject', 'subject-math', '--topics', 'topic-algebra', '--file', f.input]); const hash = createHash('sha256').update(pdf).digest('hex'); const manifest = path.join(f.root, 'deployed-assets.json'); fs.writeFileSync(manifest, JSON.stringify({ version: 1, generatedAt: new Date().toISOString(), assetIds: [hash], storageKeys: [`files/${hash}.pdf`] })); const denied = spawnSync(cli, [path.join(repo, 'scripts/ingest.ts'), 'gc', '--deployed-manifest', manifest], { cwd: f.root, encoding: 'utf8' }); assert.notEqual(denied.status, 0); run(f.root, ['gc', '--deployed-manifest', manifest, '--confirm-deployment', 'verified', '--retention-days', '0']); assert.equal(validateCatalog(f.root).assets[0].status, 'available'); });
test('adding archived matching content restores it before a published reference is written', () => { const f = setup(); const hash = createHash('sha256').update(pdf).digest('hex'); fs.mkdirSync(path.join(f.root, '.storage/r2/archive'), { recursive: true }); fs.renameSync(path.join(f.root, '.storage/r2/files'), path.join(f.root, '.storage/r2/files-empty')); fs.writeFileSync(path.join(f.root, '.storage/r2/archive', `${hash}.pdf`), pdf); fs.writeFileSync(path.join(f.root, 'content/assets.jsonl'), `${JSON.stringify({ id: hash, sha256: hash, originalFilename: 'old.pdf', sizeBytes: pdf.byteLength, mimeType: 'application/pdf', status: 'archived', storageKey: `archive/${hash}.pdf`, checksum: `sha256:${hash}`, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z', archivedAt: '2026-01-02T00:00:00.000Z' })}\n`); run(f.root, ['add', '--id', 'material-one', '--slug', 'one', '--title', 'One', '--description', 'One.', '--subject', 'subject-math', '--topics', 'topic-algebra', '--file', f.input]); const asset = validateCatalog(f.root).assets[0]; assert.equal(asset.status, 'available'); assert.ok(fs.existsSync(path.join(f.root, '.storage/r2/files', `${hash}.pdf`))); });
