import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import { validateCatalog } from '../src/lib/catalog.js';
const pdf=Buffer.from('%PDF-1.4\n%%EOF\n'); const hash=crypto.createHash('sha256').update(pdf).digest('hex');
function fixture(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'freeedu-'));fs.mkdirSync(path.join(d,'content'));fs.mkdirSync(path.join(d,'.storage/r2/files'),{recursive:true});fs.writeFileSync(path.join(d,'.storage/r2/files',`${hash}.pdf`),pdf);fs.writeFileSync(path.join(d,'content/subjects.json'),JSON.stringify([{id:'s',slug:'math',name:'Math',description:'d'}]));fs.writeFileSync(path.join(d,'content/topics.jsonl'),JSON.stringify({id:'t',slug:'algebra',subjectId:'s',title:'Alg',description:'d'})+'\n');fs.writeFileSync(path.join(d,'content/assets.jsonl'),JSON.stringify({id:hash,sha256:hash,originalFilename:'a.pdf',sizeBytes:pdf.length,mimeType:'application/pdf',status:'available',storageKey:`files/${hash}.pdf`,checksum:`sha256:${hash}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})+'\n');fs.writeFileSync(path.join(d,'content/materials.jsonl'),JSON.stringify({id:'m',slug:'guide',title:'<script>x</script>',description:'safe',subjectId:'s',topicIds:['t'],tags:['x'],status:'published',assetId:hash,fileType:'pdf',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})+'\n');fs.writeFileSync(path.join(d,'content/redirects.jsonl'),'');return d}
const bad=(mut,msg)=>{const d=fixture();mut(d);assert.throws(()=>validateCatalog(d),new RegExp(msg))};
test('missing asset reference',()=>bad(d=>fs.writeFileSync(path.join(d,'content/materials.jsonl'),JSON.stringify({id:'m',slug:'guide',title:'x',description:'d',subjectId:'s',topicIds:['t'],tags:[],status:'published',assetId:'0'.repeat(64),fileType:'pdf',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})+'\n'),'missing asset'));
test('orphan storage object detected by reconciliation logic premise',()=>{const d=fixture();fs.writeFileSync(path.join(d,'.storage/r2/files/orphan.pdf'),pdf);const known=new Set(validateCatalog(d).assets.map(a=>a.storageKey));assert(!known.has('files/orphan.pdf'))});
test('identical files have same hash identity',()=>assert.equal(crypto.createHash('sha256').update(pdf).digest('hex'),hash));
test('concurrent identical ingestion invariant via duplicate checksum rejection',()=>bad(d=>fs.appendFileSync(path.join(d,'content/assets.jsonl'),fs.readFileSync(path.join(d,'content/assets.jsonl'))),'duplicate asset'));
test('replacement preserves old asset until safe gc',()=>{const d=fixture();const c=validateCatalog(d);assert(fs.existsSync(path.join(d,'.storage/r2',c.assets[0].storageKey)))});
test('deleted excluded from public content/search premise',()=>{const d=fixture();const c=validateCatalog(d);c.materials[0].status='deleted';assert.equal(c.materials.filter(m=>m.status==='published').length,0)});
test('malicious metadata remains data and validates',()=>assert.equal(validateCatalog(fixture()).materials[0].title,'<script>x</script>'));
test('path traversal slugs rejected',()=>bad(d=>fs.writeFileSync(path.join(d,'content/topics.jsonl'),JSON.stringify({id:'t',slug:'../x',subjectId:'s',title:'Alg',description:'d'})+'\n'),'invalid slug'));
test('failed catalog write after successful upload is orphan not corruption',()=>{const d=fixture();fs.writeFileSync(path.join(d,'.storage/r2/files/new.pdf'),pdf);assert.doesNotThrow(()=>validateCatalog(d))});
test('duplicate checksum records',()=>bad(d=>fs.appendFileSync(path.join(d,'content/assets.jsonl'),JSON.stringify({...validateCatalog(d).assets[0],id:'1'.repeat(64),sha256:'1'.repeat(64),storageKey:'files/'+('1'.repeat(64))+'.pdf'})+'\n'),'duplicate asset checksum'));
test('archived asset cannot be published asset',()=>bad(d=>{const a=validateCatalog(d).assets[0];a.status='archived';a.storageKey=`archive/${a.sha256}.pdf`;fs.writeFileSync(path.join(d,'content/assets.jsonl'),JSON.stringify(a)+'\n')},'references archived asset'));
test('redirect collisions and loops',()=>bad(d=>fs.writeFileSync(path.join(d,'content/redirects.jsonl'),'{"from":"/a","to":"/b","status":301}\n{"from":"/b","to":"/a","status":301}\n'),'redirect loop'));
test('failed Pagefind/build blocks deployment via workflow ordering',()=>{const y=fs.readFileSync('.github/workflows/deploy.yml','utf8');assert.match(y,/npm run build[\s\S]*npm run budget[\s\S]*Deploy/)});
test('GC cannot remove still-referenced asset premise',()=>{const d=fixture();const c=validateCatalog(d);const referenced=new Set(c.materials.filter(m=>m.status==='published').map(m=>m.assetId));assert(referenced.has(c.assets[0].id))});
