import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Command } from 'commander';
import { loadCatalog, localObjectReader, validateCatalog, type Asset, type Catalog, type Material } from '../src/lib/catalog.ts';
import { readDeploymentManifest } from '../src/lib/manifest.ts';

const MAX_PDF_BYTES = 50 * 1024 * 1024; const ROOT = process.cwd();
const now = () => new Date().toISOString(); const sha = (data: Buffer) => createHash('sha256').update(data).digest('hex');
type Input = { bytes: Buffer; hash: string; size: number; filename: string };
function readPdf(file: string): Input { const bytes = fs.readFileSync(file); if (bytes.byteLength === 0 || bytes.byteLength > MAX_PDF_BYTES) throw new Error(`PDF must be between 1 and ${MAX_PDF_BYTES} bytes`); if (bytes.subarray(0, 5).toString() !== '%PDF-') throw new Error('input is not a PDF: magic bytes are missing'); return { bytes, hash: sha(bytes), size: bytes.byteLength, filename: path.basename(file) }; }
function catalogFiles() { return ['content/assets.jsonl', 'content/materials.jsonl']; }
function writeJsonl(file: string, rows: unknown[]) { const temporary = `${file}.${process.pid}.${Date.now()}.tmp`; fs.writeFileSync(temporary, `${rows.map((row) => JSON.stringify(row)).join('\n')}\n`, { mode: 0o600 }); fs.renameSync(temporary, file); }
function saveCatalog(catalog: Catalog) { writeJsonl('content/assets.jsonl', catalog.assets); writeJsonl('content/materials.jsonl', catalog.materials); }
async function lock<T>(action: () => Promise<T> | T): Promise<T> { const lockPath = path.join(ROOT, 'content', '.ingest.lock'); let fd: number | undefined; for (let attempt = 0; attempt < 100; attempt += 1) { try { fd = fs.openSync(lockPath, 'wx', 0o600); break; } catch { await new Promise((resolve) => setTimeout(resolve, 25)); } } if (fd === undefined) throw new Error('catalog lock is busy; retry safely'); try { return await action(); } finally { fs.closeSync(fd); fs.unlinkSync(lockPath); } }
function storageFile(storage: string, key: string) { if (!/^(files|archive)\/[a-f0-9]{64}\.pdf$/.test(key)) throw new Error(`unsafe storage key ${key}`); return path.join(storage, key); }
function ensureAvailable(storage: string, input: Input): string { const key = `files/${input.hash}.pdf`; const destination = storageFile(storage, key); fs.mkdirSync(path.dirname(destination), { recursive: true }); if (!fs.existsSync(destination)) { const temporary = `${destination}.${process.pid}.tmp`; fs.writeFileSync(temporary, input.bytes, { mode: 0o600 }); fs.renameSync(temporary, destination); } const stored = fs.readFileSync(destination); if (sha(stored) !== input.hash || stored.byteLength !== input.size || stored.subarray(0, 5).toString() !== '%PDF-') throw new Error(`local test storage verification failed for ${key}`); return key; }
function assetFor(input: Input, key: string): Asset { const time = now(); return { id: input.hash, sha256: input.hash, originalFilename: input.filename, sizeBytes: input.size, mimeType: 'application/pdf', status: 'available', storageKey: key, checksum: `sha256:${input.hash}`, createdAt: time, updatedAt: time }; }
function restoreArchived(storage: string, asset: Asset, input: Input) { const archived = storageFile(storage, asset.storageKey); const available = storageFile(storage, `files/${asset.sha256}.pdf`); fs.mkdirSync(path.dirname(available), { recursive: true }); if (fs.existsSync(archived)) fs.renameSync(archived, available); else ensureAvailable(storage, input); asset.status = 'available'; asset.storageKey = `files/${asset.sha256}.pdf`; asset.restoredAt = now(); asset.updatedAt = now(); delete asset.archivedAt; }
function rollback(files: Map<string, Buffer>, storageCreated?: string) { for (const [file, content] of files) fs.writeFileSync(file, content); if (storageCreated && fs.existsSync(storageCreated)) fs.unlinkSync(storageCreated); }
async function add(options: Record<string, string>) { await lock(() => { const input = readPdf(options.file); const storage = options.storage ?? '.storage/r2'; const before = new Map(catalogFiles().map((file) => [file, fs.readFileSync(file)])); const catalog = loadCatalog(); if (catalog.materials.some((material) => material.id === options.id || material.slug === options.slug)) throw new Error('material id or slug is reserved, including deleted history'); let asset = catalog.assets.find((entry) => entry.sha256 === input.hash); const created = !asset; const key = ensureAvailable(storage, input); try { if (!asset) { asset = assetFor(input, key); catalog.assets.push(asset); } else if (asset.status === 'archived') restoreArchived(storage, asset, input); const time = now(); const material: Material = { id: options.id, slug: options.slug, title: options.title, description: options.description, subjectId: options.subject, topicIds: options.topics.split(',').filter(Boolean), tags: (options.tags ?? '').split(',').filter(Boolean), status: 'published', assetId: asset.id, fileType: 'pdf', createdAt: time, updatedAt: time }; catalog.materials.push(material); saveCatalog(catalog); validateCatalog(ROOT, localObjectReader(ROOT, storage)); console.log(`added ${material.id} using ${asset.id}`); } catch (error) { rollback(before, created ? storageFile(storage, key) : undefined); throw error; } }); }
async function replace(id: string, file: string, options: Record<string, string>) { await lock(() => { const input = readPdf(file); const storage = options.storage ?? '.storage/r2'; const before = new Map(catalogFiles().map((entry) => [entry, fs.readFileSync(entry)])); const catalog = loadCatalog(); const material = catalog.materials.find((entry) => entry.id === id && entry.status !== 'deleted'); if (!material) throw new Error('active material not found'); let asset = catalog.assets.find((entry) => entry.sha256 === input.hash); const created = !asset; const key = ensureAvailable(storage, input); try { if (!asset) { asset = assetFor(input, key); catalog.assets.push(asset); } else if (asset.status === 'archived') restoreArchived(storage, asset, input); material.assetId = asset.id; material.updatedAt = now(); saveCatalog(catalog); validateCatalog(ROOT, localObjectReader(ROOT, storage)); console.log(`replaced ${id}; previous asset remains protected until verified deployment GC`); } catch (error) { rollback(before, created ? storageFile(storage, key) : undefined); throw error; } }); }
async function remove(id: string, options: Record<string, string>) { await lock(() => { const storage = options.storage ?? '.storage/r2'; const catalog = loadCatalog(); const material = catalog.materials.find((entry) => entry.id === id); if (!material) throw new Error('material not found'); material.status = 'deleted'; material.deletedAt = now(); material.updatedAt = now(); saveCatalog(catalog); validateCatalog(ROOT, localObjectReader(ROOT, storage)); console.log(`marked ${id} deleted`); }); }
function reconcile(storage: string) { const catalog = validateCatalog(ROOT, localObjectReader(ROOT, storage)); const reader = localObjectReader(ROOT, storage); const known = new Set(catalog.assets.map((asset) => asset.storageKey)); const errors = [...reader.list('files/'), ...reader.list('archive/')].filter((key) => !known.has(key)).map((key) => `orphan local test object: ${key}`); if (errors.length) throw new Error(errors.join('\n')); console.log('local test storage reconciliation passed'); }
async function gc(options: Record<string, string>) { if (options.confirmDeployment !== 'verified') throw new Error('refusing GC: --confirm-deployment verified is required after smoke tests'); await lock(() => { const storage = options.storage ?? '.storage/r2'; const manifest = readDeploymentManifest(options.deployedManifest); const catalog = loadCatalog(); const protectedIds = new Set([...manifest.assetIds, ...catalog.materials.filter((material) => material.status === 'published').map((material) => material.assetId)]); const cutoff = Date.now() - Number(options.retentionDays) * 86_400_000; for (const asset of catalog.assets) { if (asset.status !== 'available' || protectedIds.has(asset.id) || Date.parse(asset.updatedAt) > cutoff) continue; const source = storageFile(storage, asset.storageKey); const destination = storageFile(storage, `archive/${asset.sha256}.pdf`); if (!fs.existsSync(source)) throw new Error(`refusing GC: source missing ${asset.storageKey}`); fs.mkdirSync(path.dirname(destination), { recursive: true }); fs.renameSync(source, destination); asset.status = 'archived'; asset.storageKey = `archive/${asset.sha256}.pdf`; asset.archivedAt = now(); asset.updatedAt = now(); }
  saveCatalog(catalog); validateCatalog(ROOT, localObjectReader(ROOT, storage)); console.log('local test storage GC completed'); }); }
const cli = new Command(); cli.name('freeedu-ingest');
cli.command('add').requiredOption('--file <file>').requiredOption('--id <id>').requiredOption('--slug <slug>').requiredOption('--title <title>').requiredOption('--description <description>').requiredOption('--subject <id>').requiredOption('--topics <ids>').option('--tags <tags>', '').option('--storage <dir>', '.storage/r2').action(add);
cli.command('replace <id> <file>').option('--storage <dir>', '.storage/r2').action(replace);
cli.command('delete <id>').option('--storage <dir>', '.storage/r2').action(remove);
cli.command('reconcile').option('--storage <dir>', '.storage/r2').action((options) => reconcile(options.storage));
cli.command('gc').requiredOption('--deployed-manifest <file>').requiredOption('--confirm-deployment <value>').option('--retention-days <days>', '30').option('--storage <dir>', '.storage/r2').action(gc);
cli.parseAsync().catch((error) => { console.error(error.message); process.exitCode = 1; });
