import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import { Command } from 'commander';import lockfile from 'proper-lockfile';import { loadCatalog, validateCatalog } from '../src/lib/catalog.js';
const MAX=50*1024*1024; const now=()=>new Date().toISOString(); const root=process.cwd();
function shaFile(f:string){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')}
function verifyPdf(f:string){const b=fs.readFileSync(f); if(b.length>MAX)throw Error('PDF exceeds max size'); if(b.subarray(0,5).toString()!=='%PDF-')throw Error('file is not a PDF by magic bytes'); return b.length}
function atomicAppend(file:string,line:string){const tmp=`${file}.${process.pid}.tmp`; fs.writeFileSync(tmp,fs.existsSync(file)?fs.readFileSync(file):''); fs.appendFileSync(tmp,line+'\n'); fs.renameSync(tmp,file)}
async function withLock<T>(fn:()=>Promise<T>|T){fs.mkdirSync('content',{recursive:true}); const release=await lockfile.lock('content',{retries:{retries:10,factor:1,minTimeout:50,maxTimeout:100}}); try{return await fn()} finally{await release()}}
function upload(storage:string,file:string,hash:string){const key=`files/${hash}.pdf`,dest=path.join(storage,key); fs.mkdirSync(path.dirname(dest),{recursive:true}); if(!fs.existsSync(dest))fs.copyFileSync(file,dest); if(shaFile(dest)!==hash)throw Error('upload verification failed'); return key}
async function add(o:any){await withLock(()=>{const size=verifyPdf(o.file),hash=shaFile(o.file),c=loadCatalog(root); let a=c.assets.find((x:any)=>x.sha256===hash); const key=upload(o.storage, o.file, hash); if(!a)atomicAppend('content/assets.jsonl',JSON.stringify({id:hash,sha256:hash,originalFilename:path.basename(o.file),sizeBytes:size,mimeType:'application/pdf',status:'available',storageKey:key,checksum:`sha256:${hash}`,createdAt:now(),updatedAt:now()})); const mat={id:o.id,slug:o.slug,title:o.title,description:o.description,subjectId:o.subject,topicIds:o.topics.split(','),tags:(o.tags||'').split(',').filter(Boolean),status:'published',assetId:hash,fileType:'pdf',createdAt:now(),updatedAt:now()}; atomicAppend('content/materials.jsonl',JSON.stringify(mat)); validateCatalog(root,{checkStorage:true,storageRoot:o.storage}); console.log(`added ${o.id} using asset ${hash}`)})}
async function replace(id:string,file:string,o:any){await withLock(()=>{const size=verifyPdf(file),hash=shaFile(file),c=loadCatalog(root),m=c.materials.find((x:any)=>x.id===id&&x.status!=='deleted'); if(!m)throw Error('material not found'); const key=upload(o.storage,file,hash); if(!c.assets.some((a:any)=>a.sha256===hash))atomicAppend('content/assets.jsonl',JSON.stringify({id:hash,sha256:hash,originalFilename:path.basename(file),sizeBytes:size,mimeType:'application/pdf',status:'available',storageKey:key,checksum:`sha256:${hash}`,createdAt:now(),updatedAt:now()})); m.assetId=hash;m.updatedAt=now(); fs.writeFileSync('content/materials.jsonl',c.materials.map((x:any)=>JSON.stringify(x)).join('\n')+'\n'); validateCatalog(root,{checkStorage:true,storageRoot:o.storage}); console.log(`replaced ${id}; old asset preserved until post-deploy gc`)})}
async function del(id:string){await withLock(()=>{const c=loadCatalog(root),m=c.materials.find((x:any)=>x.id===id); if(!m)throw Error('material not found'); m.status='deleted';m.deletedAt=now();m.updatedAt=now(); fs.writeFileSync('content/materials.jsonl',c.materials.map((x:any)=>JSON.stringify(x)).join('\n')+'\n'); validateCatalog(root,{checkStorage:true,storageRoot:'.storage/r2'}); console.log(`deleted ${id}`)})}
function reconcile(storage:string){const c=validateCatalog(root,{checkStorage:true,storageRoot:storage}),known=new Set(c.assets.map((a:any)=>a.storageKey)); const errs:string[]=[]; for(const p of ['files','archive']){const d=path.join(storage,p); if(fs.existsSync(d))for(const f of fs.readdirSync(d)){const k=`${p}/${f}`; if(!known.has(k))errs.push(`storage object missing from catalog: ${k}`)}} for(const p of fs.existsSync(storage)?fs.readdirSync(storage):[])if(!['files','archive'].includes(p))errs.push(`unexpected prefix: ${p}`); if(errs.length){console.error(errs.join('\n'));process.exit(1)} console.log('reconciliation passed')}
function gc(storage:string, deployedManifest:string){const deployed=new Set(JSON.parse(fs.readFileSync(deployedManifest,'utf8')).assetIds),c=loadCatalog(root),referenced=new Set(c.materials.filter((m:any)=>m.status==='published').map((m:any)=>m.assetId)); for(const a of c.assets){if(a.status==='available'&&!referenced.has(a.id)&&!deployed.has(a.id)){const src=path.join(storage,a.storageKey),dst=path.join(storage,'archive',`${a.sha256}.pdf`); if(fs.existsSync(src)){fs.mkdirSync(path.dirname(dst),{recursive:true}); fs.renameSync(src,dst); a.status='archived';a.storageKey=`archive/${a.sha256}.pdf`;a.archivedAt=now();a.updatedAt=now(); fs.writeFileSync('content/assets.jsonl',c.assets.map((x:any)=>JSON.stringify(x)).join('\n')+'\n')}}} validateCatalog(root,{checkStorage:true,storageRoot:storage}); console.log('gc complete')}
const p=new Command();p.command('add').requiredOption('--file <file>').requiredOption('--id <id>').requiredOption('--slug <slug>').requiredOption('--title <title>').requiredOption('--description <text>').requiredOption('--subject <id>').requiredOption('--topics <ids>').option('--tags <tags>').option('--storage <dir>','.storage/r2').action(add);p.command('replace <id> <file>').option('--storage <dir>','.storage/r2').action(replace);p.command('delete <id>').action(del);p.command('reconcile').option('--storage <dir>','.storage/r2').action(o=>reconcile(o.storage));p.command('gc').requiredOption('--deployed-manifest <file>').option('--storage <dir>','.storage/r2').action(o=>gc(o.storage,o.deployedManifest));p.parse();
