/** Production-only R2 transport. It requires Wrangler credentials and is never backed by .storage/r2. */
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Command } from 'commander';
import { readDeploymentManifest } from '../src/lib/manifest.ts';
import { loadCatalog } from '../src/lib/catalog.ts';

function wrangler(args: string[]) { const result = spawnSync('wrangler', args, { encoding: 'utf8' }); if (result.status !== 0) throw new Error(`wrangler ${args.join(' ')} failed:\n${result.stderr || result.stdout}`); return result.stdout; }
function verifyFile(file: string, expected: string) { const bytes = fs.readFileSync(file); if (createHash('sha256').update(bytes).digest('hex') !== expected || bytes.subarray(0, 5).toString() !== '%PDF-') throw new Error(`R2 object ${expected} failed SHA-256 or PDF magic verification`); }
function requireBucket(value: string | undefined) { if (!value || !/^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$/.test(value)) throw new Error('R2 bucket name is required and must be a valid bucket name'); return value; }
function upload(options: { bucket?: string; manifest: string; source: string }) { const bucket = requireBucket(options.bucket); const manifest = readDeploymentManifest(options.manifest); for (const key of manifest.storageKeys) { const hash = path.basename(key, '.pdf'); const source = path.join(options.source, key); verifyFile(source, hash); wrangler(['r2', 'object', 'put', `${bucket}/${key}`, '--file', source, '--remote']); const temporary = path.join(os.tmpdir(), `freeedu-r2-${hash}-${process.pid}.pdf`); try { wrangler(['r2', 'object', 'get', `${bucket}/${key}`, '--file', temporary, '--remote']); verifyFile(temporary, hash); } finally { fs.rmSync(temporary, { force: true }); } } console.log(`uploaded and verified ${manifest.storageKeys.length} R2 object(s)`); }
function verify(options: { bucket?: string; manifest: string }) { const bucket = requireBucket(options.bucket); const manifest = readDeploymentManifest(options.manifest); for (const key of manifest.storageKeys) { const hash = path.basename(key, '.pdf'); const temporary = path.join(os.tmpdir(), `freeedu-r2-${hash}-${process.pid}.pdf`); try { wrangler(['r2', 'object', 'get', `${bucket}/${key}`, '--file', temporary, '--remote']); verifyFile(temporary, hash); } finally { fs.rmSync(temporary, { force: true }); } } console.log(`verified ${manifest.storageKeys.length} deployed R2 object(s)`); }
function reconcile(options: { bucket?: string }) { const bucket = requireBucket(options.bucket); const catalog = loadCatalog(); const expected = new Set(catalog.assets.map((asset) => asset.storageKey)); const actual = new Set<string>(); for (const prefix of ['files/', 'archive/']) { const output = wrangler(['r2', 'object', 'list', bucket, '--prefix', prefix, '--remote', '--json']); const parsed: unknown = JSON.parse(output); const entries = Array.isArray(parsed) ? parsed : (parsed as { objects?: unknown[] }).objects; if (!Array.isArray(entries)) throw new Error('unexpected Wrangler R2 list response'); for (const entry of entries) { const key = typeof entry === 'string' ? entry : (entry as { key?: unknown }).key; if (typeof key !== 'string') throw new Error('unexpected R2 object list entry'); actual.add(key); } }
  const errors = [...expected].filter((key) => !actual.has(key)).map((key) => `catalog asset missing in R2: ${key}`).concat([...actual].filter((key) => !expected.has(key)).map((key) => `R2 orphan object: ${key}`)); if (errors.length) throw new Error(errors.join('\n')); console.log('R2 reconciliation passed'); }
const cli = new Command(); cli.name('freeedu-r2'); cli.command('upload').requiredOption('--bucket <bucket>').requiredOption('--manifest <file>').requiredOption('--source <directory>').action(upload); cli.command('verify').requiredOption('--bucket <bucket>').requiredOption('--manifest <file>').action(verify); cli.command('reconcile').requiredOption('--bucket <bucket>').action(reconcile); cli.parseAsync().catch((error) => { console.error(error.message); process.exitCode = 1; });
